package com.pandiandcode.cardsagainsthumanity.domain

class WhiteDeckRepository {
    fun load(): List<Card> =
        listOf(
            Card("50.000 voltios directamente en los pezones"),
            Card("72 vírgenes."),
            Card("300 gramos de dulce heroína negra Mexicana."),
            Card("Una bolsa de habichuelas mágicas."),
            Card("Un desayuno equilibrado."),
            Card("Una bola de cera de oreja, semen y recortes de uñas."),
            Card("Un bofetón de zorra."),
            Card("Un agujero del culo blanqueado."),
            Card("Un juego de Bop ItTM."),
            Card("Un tumor cerebral."),
            Card("Un cubo con cabezas de pescado."),
            Card("Una lata de hostias."),
            Card("Una nevera llena de órganos."),
            Card("Un condón defectuoso."),
            Card("Una fiesta de cumpleaños decepcionante."),
            Card("Un halcón con un gorro en la cabeza."),
            Card("Un feto."),
            Card("Un masturbador masculino. (Fleshlight)"),
            Card("Un antílope con gases."),
            Card("Una caricia suave en la parte de dentro del muslo."),
            Card("Una buena esnifada."),
            Card("Un montaje homoerótico sobre voleibol."),
            Card("Una vida de tristeza"),
            Card("Una audiencia de estudio en directo."),
            Card("Un hombre al borde del orgasmo."),
            Card("Un ritual de apareamiento."),
            Card("Un micropene."),
            Card("Un cerdo diminuto llevando un chubasquero pequeñito y botas de agua."),
            Card("Un hombre de mediana edad en patines."),
            Card("Un mimo teniendo un ataque al corazón."),
            Card("Un mono fumando un puro."),
            Card("Un leon de zoo deprimido."),
            Card("Un asesinato muy vil."),
            Card("Una pirámide de cabezas cortadas."),
            Card("Un sombrero muy guay."),
            Card("Un mongoloide robusto."),
            Card("Una triste paja."),
            Card("Una corrida en la boca sin avisar."),
            Card("Una mujer negra con mucha chispa."),
            Card("Un solo de saxofón."),
            Card("Un mar de problemas."),
            Card("Una tortuga mordiéndote la punta del pene."),
            Card("Un pelo del pubis solitario."),
            Card("Una subscripción a Men ́s Fitness."),
            Card("Una pistola de agua llena de pis de gato."),
            Card("Una explosión termonuclear."),
            Card("Una paradoja de viajes en el tiempo."),
            Card("Un mini caballo."),
            Card("Una tribu de mujeres guerreras."),
            Card("Un molino lleno de cadáveres."),
            Card("Un intenso burrito para desayunar."),
            Card("Aaron Burr."),
            Card("Escuchar activamente."),
            Card("Anfetaminas (AdderallTM)."),
            Card("Consejos de un viejo y sabio hombre negro."),
            Card("Niños africanos."),
            Card("Agricultura."),
            Card("SIDA."),
            Card("Alcoholismo."),
            Card("Buffet Libre de gambas por $4.99."),
            Card("Monaguillos."),
            Card("Amputados."),
            Card("Un aumento de pechos asimétrico.")
        )
}